ignoreWorkspaceRootCheck: true
shamefullyHoist: true
strictPeerDependencies: false
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - examples/*

catalog:
  '@antfu/eslint-config': ^7.2.0
  '@nuxt/devalue': ^2.0.2
  '@types/html-minifier-terser': ^7.0.2
  '@types/jsdom': ^27.0.0
  '@unhead/dom': ^2.1.2
  '@unhead/vue': ^2.1.2
  '@vitejs/plugin-vue': ^6.0.4
  ansis: ^4.2.0
  beasties: ^0.4.1
  bumpp: ^10.4.0
  cac: ^6.7.14
  eslint: ^9.39.2
  html-minifier-terser: ^7.2.0
  html5parser: ^2.0.2
  jsdom: ^28.0.0
  p-queue: ^9.1.0
  pinia: ^3.0.4
  prettier: ^3.8.1
  rollup: ^4.57.1
  semver: ^7.7.3
  tinyglobby: ^0.2.15
  tsx: ^4.21.0
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unplugin-vue-components: ^31.0.0
  unplugin-vue-markdown: ^29.2.0
  vite: ^7.3.1
  vite-plugin-pages: ^0.33.3
  vite-plugin-pwa: ^1.2.0
  vitest: ^4.0.18
  vue: ^3.5.27
  vue-router: ^5.0.2
  vue-tsc: ^3.2.4
  workbox-build: ^7.4.0
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
